pr: none
trigger: none

pool:
  vmImage: ubuntu-20.04

variables:
  buildVersion: 0.0.0

steps:
- checkout: self
  fetchDepth: 0

- task: NodeTool@0
  inputs:
    versionSpec: '14.x'

- bash: |
    version=14.0.0-alpha-$(git rev-list --count $BUILD_SOURCEVERSION)
    echo 'New version='$version
    echo "##vso[task.setvariable variable=buildVersion;]$version"
  displayName: Setup new version

- bash: |
    echo '##vso[build.updatebuildnumber]$(buildVersion)'
  displayName: Set build name

- bash: |
    git config --global user.email "jon@dealbridge.net"
    git config --global user.name "Jon Burlinson"
    npm version $(buildVersion)
  displayName: Set package version

- task: npmAuthenticate@0
  inputs:
    workingFile: $(System.DefaultWorkingDirectory)/.npmrc
  displayName: npm authenticate

- bash: |
    cat .npmrc
    yarn install --frozen-lockfile
  displayName: yarn install

- bash: |
    npm run build:npm
  displayName: build

- bash: npm publish
  displayName: publish
